#!/bin/bash

# This file is a stub  for the real IAR "iasmarm.exe".
# Put this on your path to launch the assembler with the "iasmarm" command.

#Example :
#$HOME/.wine/drive_c/Program\ Files\ \(x86\)/IAR\ Systems/Embedded\ Workbench\ 6.0\ Kickstart/arm/bin/iasmarm.exe $*
#C:\Program Files\IAR Systems\Embedded Workbench 6.0\arm\bin\iasmarm.exe $*

#remove or comment the following once the file is properly edited
echo "Please edit the file $( cd $(dirname $0) ; pwd -P )/$(basename $0)"